# Generated by Django 5.0.3 on 2024-03-26 09:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("supervisor", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="localites",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="sex",
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="tel",
            field=models.CharField(max_length=20, null=True),
        ),
    ]
